CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "current_team_id" integer, "profile_photo_path" varchar, "created_at" datetime, "updated_at" datetime, "two_factor_secret" text, "two_factor_recovery_codes" text, "two_factor_confirmed_at" datetime);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE TABLE IF NOT EXISTS "password_resets" ("email" varchar not null, "token" varchar not null, "created_at" datetime);
CREATE INDEX "password_resets_email_index" on "password_resets" ("email");
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" varchar not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE TABLE IF NOT EXISTS "expenses" ("id" varchar not null, "name" varchar not null, "category_id" varchar, "description" varchar, "amount" numeric not null, "transaction_date" date not null, "due_date" date, "paid_date" date, "payment_type_id" varchar not null, "currency_id" varchar not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "user_id" integer, "payment_to_id" varchar, primary key ("id"));
CREATE TABLE IF NOT EXISTS "payment_types" ("id" varchar not null, "name" varchar not null, "description" varchar, "user_id" integer, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE IF NOT EXISTS "currencies" ("id" varchar not null, "name" varchar not null, "code" varchar not null, "symbol" varchar, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE IF NOT EXISTS "categories" ("id" varchar not null, "name" varchar not null, "budget" numeric not null, "parent_id" varchar, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE IF NOT EXISTS "category_expense" ("category_id" varchar not null, "expense_id" varchar not null);
CREATE TABLE IF NOT EXISTS "events" ("id" varchar not null, "user_id" integer not null, "title" varchar not null, "description" text, "intervals" integer not null default '12', "reminder" integer not null default '60', "event_date" datetime not null, "action_date" datetime, "status" varchar not null default 'active', "is_private" tinyint(1) not null default '1', "is_owed" tinyint(1), "currency_id" integer, "amount" numeric, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, primary key ("id"));
CREATE TABLE IF NOT EXISTS "daily_tasks" ("id" varchar not null, "user_id" integer not null, "title" varchar not null, "description" text, "planned_time" datetime, "completed_time" datetime, "deadline" datetime, "status" varchar not null default 'active', "is_private" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, primary key ("id"));
INSERT INTO migrations VALUES(1,'2014_10_12_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'2014_10_12_100000_create_password_resets_table',1);
INSERT INTO migrations VALUES(3,'2014_10_12_200000_add_two_factor_columns_to_users_table',1);
INSERT INTO migrations VALUES(4,'2019_08_19_000000_create_failed_jobs_table',1);
INSERT INTO migrations VALUES(5,'2019_12_14_000001_create_personal_access_tokens_table',1);
INSERT INTO migrations VALUES(6,'2022_12_22_064129_create_sessions_table',1);
INSERT INTO migrations VALUES(7,'2022_12_22_080332_create_expenses_table',1);
INSERT INTO migrations VALUES(8,'2022_12_22_081643_create_payment_types_table',1);
INSERT INTO migrations VALUES(9,'2023_02_08_022030_create_currencies_table',1);
INSERT INTO migrations VALUES(10,'2023_02_11_170343_create_categories_table',1);
INSERT INTO migrations VALUES(11,'2023_02_11_170514_create_category_expense_table',1);
INSERT INTO migrations VALUES(12,'2023_03_21_032342_create_events_table',1);
INSERT INTO migrations VALUES(13,'2023_09_05_030513_add_softdelete_column_to_expenses_table',1);
INSERT INTO migrations VALUES(14,'2023_09_11_094043_add_user_id_to_expenses_table',1);
INSERT INTO migrations VALUES(15,'2023_10_09_030250_add_payment_destination_to_expenses_table',1);
INSERT INTO migrations VALUES(16,'2024_02_13_025449_create_daily_tasks_table',1);
